In [31]:
import pandas as pd

In [32]:
bran = pd.read_csv('../model_ready_data.csv')

In [33]:
bran.head() #brandon's google mobility data _ closing prices and financial / commodity metrics

,date,phillips_66,bp_plc,valero_energy_corporation,chevron_corporation,occidental_petroleum_corporation,marathon_oil_corporation,pioneer_natural_resources_company,conocophillips,exxon_mobil_corporation,...,dow_jones_industrial_average,dow_jones_utility_average,workplaces,retail_and_recreation,grocery_and_pharmacy,residential,transit_stations,parks,int_news_sentiment,na_news_sentiment
0,2020-02-18,88.00,36.09,82.52,110.24,41.56,10.30,135.56,58.30,59.88,...,29232.19,960.89,-0.006305,-0.211659,-1.377153,1.345745,2.440042,5.466077,0.0,0.0
1,2020-02-19,88.36,36.25,83.23,110.74,42.51,10.47,141.17,59.26,60.34,...,29348.03,950.01,1.001656,2.222899,0.639556,0.345455,2.634615,8.153166,0.0,0.0
2,2020-02-20,90.19,35.98,84.17,109.81,42.97,10.25,142.53,58.88,59.86,...,29219.98,952.40,-0.387448,0.192474,-0.167570,1.922258,2.098260,-1.300847,-0.2,0.0
3,2020-02-21,89.25,35.36,82.90,109.01,42.12,10.11,142.25,58.44,59.13,...,28992.41,948.74,0.547162,2.786383,-1.632662,1.082046,3.656008,6.725381,0.0,0.0
4,2020-02-24,86.56,34.06,78.10,104.71,39.48,9.46,135.97,56.38,56.36,...,27960.80,935.91,3.010224,1.766222,0.129503,0.641213,0.961066,7.336245,0.1,0.0

In [34]:
bran.set_index(pd.to_datetime(bran['date']), inplace=True)
bran.drop(columns='date', inplace=True)
bran.sort_index(inplace=True)#sort by date
bran #confirm changes

,phillips_66,bp_plc,valero_energy_corporation,chevron_corporation,occidental_petroleum_corporation,marathon_oil_corporation,pioneer_natural_resources_company,conocophillips,exxon_mobil_corporation,marathon_petroleum_corporation,...,dow_jones_industrial_average,dow_jones_utility_average,workplaces,retail_and_recreation,grocery_and_pharmacy,residential,transit_stations,parks,int_news_sentiment,na_news_sentiment
date,,,,,,,,,,,,,,,,,,,,,
2020-02-18,88.00,36.09,82.52,110.24,41.56,10.30,135.56,58.30,59.88,56.47,...,29232.19,960.89,-0.006305,-0.211659,-1.377153,1.345745,2.440042,5.466077,0.00,0.00
2020-02-19,88.36,36.25,83.23,110.74,42.51,10.47,141.17,59.26,60.34,57.69,...,29348.03,950.01,1.001656,2.222899,0.639556,0.345455,2.634615,8.153166,0.00,0.00
2020-02-20,90.19,35.98,84.17,109.81,42.97,10.25,142.53,58.88,59.86,60.26,...,29219.98,952.40,-0.387448,0.192474,-0.167570,1.922258,2.098260,-1.300847,-0.20,0.00
2020-02-21,89.25,35.36,82.90,109.01,42.12,10.11,142.25,58.44,59.13,59.13,...,28992.41,948.74,0.547162,2.786383,-1.632662,1.082046,3.656008,6.725381,0.00,0.00
2020-02-24,86.56,34.06,78.10,104.71,39.48,9.46,135.97,56.38,56.36,55.87,...,27960.80,935.91,3.010224,1.766222,0.129503,0.641213,0.961066,7.336245,0.10,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-19,82.31,22.87,71.53,95.80,25.42,9.45,133.94,48.42,52.37,53.00,...,31494.32,846.51,-26.703297,-20.935180,-12.503418,12.225713,-25.787372,-26.599754,0.00,0.00
2021-02-22,83.96,23.63,74.25,98.39,26.47,10.20,139.47,50.88,54.30,54.85,...,31521.69,830.38,-19.689617,-14.583490,-8.355705,8.119504,-18.301961,-17.634278,0.00,0.00
2021-02-23,85.53,24.23,75.81,99.63,26.06,11.16,145.24,52.10,55.05,55.77,...,31537.35,835.85,-19.324188,-8.923650,-3.151351,6.976641,-14.679208,2.265554,-0.27,-0.50
2021-02-24,87.25,25.30,78.16,103.31,28.16,11.84,150.06,54.67,56.70,56.65,...,31961.86,825.65,-18.923493,-6.442705,-2.626381,6.734819,-12.945525,7.219697,-0.10,-0.50
2021-02-25,84.64,25.59,78.15,102.35,26.75,11.30,149.05,53.03,55.76,55.07,...,31402.01,814.39,-19.029221,-8.706634,-3.693143,7.026578,-13.389535,-2.223188,0.00,0.07

In [35]:
bran.drop(columns=['int_news_sentiment', 'na_news_sentiment'], inplace=True) #drop old sentiment columns

In [36]:
apl = pd.read_csv('../apple_mobility_top5countries.csv')
apl.head() #preview

,Date,Value_ger_walk,Value_ger_drive,Value_ger_trans,Value_ind_walk,Value_ind_drive,Value_rus_walk,Value_rus_drive,Value_us_walk,Value_us_drive,Value_us_trans,Value_jap_walk,Value_jap_drive,Value_jap_trans
0,2020-01-13,100.000000,100.000000,100.000000,100.000000,100.000000,100.0000,100.0000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
1,2020-01-14,103.183824,100.824118,100.482778,98.036667,97.018333,103.6425,100.5600,101.940784,103.007547,99.727907,100.745745,99.272340,100.258511
2,2020-01-15,106.456471,102.264706,99.780000,100.060000,96.381667,102.9575,101.9925,101.752353,104.364528,98.963256,104.023191,100.096596,101.187447
3,2020-01-16,109.984118,104.645882,100.437778,101.966667,101.233333,108.3575,104.2175,102.251373,107.985849,99.501860,114.933830,104.993617,108.546383
4,2020-01-17,123.211176,114.010294,108.340000,110.888333,115.590000,110.8375,108.7100,121.800784,122.748868,105.785814,152.478723,130.354468,133.495532

In [37]:
apl.set_index(pd.to_datetime(apl['Date']), inplace=True)
apl.drop(columns='Date', inplace=True)
apl.sort_index(inplace=True)#sort by date
apl #confirm changes

,Value_ger_walk,Value_ger_drive,Value_ger_trans,Value_ind_walk,Value_ind_drive,Value_rus_walk,Value_rus_drive,Value_us_walk,Value_us_drive,Value_us_trans,Value_jap_walk,Value_jap_drive,Value_jap_trans
Date,,,,,,,,,,,,,
2020-01-13,100.000000,100.000000,100.000000,100.000000,100.000000,100.0000,100.0000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
2020-01-14,103.183824,100.824118,100.482778,98.036667,97.018333,103.6425,100.5600,101.940784,103.007547,99.727907,100.745745,99.272340,100.258511
2020-01-15,106.456471,102.264706,99.780000,100.060000,96.381667,102.9575,101.9925,101.752353,104.364528,98.963256,104.023191,100.096596,101.187447
2020-01-16,109.984118,104.645882,100.437778,101.966667,101.233333,108.3575,104.2175,102.251373,107.985849,99.501860,114.933830,104.993617,108.546383
2020-01-17,123.211176,114.010294,108.340000,110.888333,115.590000,110.8375,108.7100,121.800784,122.748868,105.785814,152.478723,130.354468,133.495532
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-23,97.873235,84.882647,135.176111,142.736667,123.536667,87.9200,85.9750,123.046667,113.270755,62.286279,132.853617,119.534894,105.554043
2021-02-24,101.482353,87.262647,136.272222,144.465000,126.061667,97.5275,100.7775,127.957451,117.192264,63.974884,143.045957,121.992553,108.229362
2021-02-25,100.442353,87.460588,133.856111,138.656667,119.348333,115.1050,109.7300,131.530588,121.559245,64.381163,125.468723,117.577872,103.360426
2021-02-26,92.082941,88.633824,129.355000,149.380000,131.966667,122.7575,114.6300,160.454902,142.369623,68.913488,140.038511,139.357021,117.765532
2021-02-27,94.920294,82.352941,124.637222,165.546667,151.615000,123.1400,106.6200,171.763333,140.332453,66.843256,150.516809,144.846596,122.074468

In [38]:
#merge
new = bran.join(apl) #left join mobility data (match to bran's dates)
new #preview

,phillips_66,bp_plc,valero_energy_corporation,chevron_corporation,occidental_petroleum_corporation,marathon_oil_corporation,pioneer_natural_resources_company,conocophillips,exxon_mobil_corporation,marathon_petroleum_corporation,...,Value_ind_walk,Value_ind_drive,Value_rus_walk,Value_rus_drive,Value_us_walk,Value_us_drive,Value_us_trans,Value_jap_walk,Value_jap_drive,Value_jap_trans
date,,,,,,,,,,,,,,,,,,,,,
2020-02-18,88.00,36.09,82.52,110.24,41.56,10.30,135.56,58.30,59.88,56.47,...,111.136667,110.881667,121.0250,112.4125,102.609804,110.113585,104.151163,132.844681,115.332553,116.532766
2020-02-19,88.36,36.25,83.23,110.74,42.51,10.47,141.17,59.26,60.34,57.69,...,113.446667,112.695000,121.1125,113.6975,105.910588,111.880377,103.913721,133.792553,116.544043,117.304043
2020-02-20,90.19,35.98,84.17,109.81,42.97,10.25,142.53,58.88,59.86,60.26,...,109.050000,114.625000,124.4000,118.4700,110.245490,116.827358,104.533488,138.852766,120.650213,121.288511
2020-02-21,89.25,35.36,82.90,109.01,42.12,10.11,142.25,58.44,59.13,59.13,...,120.485000,121.406667,131.1425,130.4325,144.047059,139.783396,117.642558,163.184255,150.928298,146.309362
2020-02-24,86.56,34.06,78.10,104.71,39.48,9.46,135.97,56.38,56.36,55.87,...,108.380000,110.791667,93.9600,100.7050,100.460980,106.576792,101.527209,146.738936,122.311064,122.677872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-19,82.31,22.87,71.53,95.80,25.42,9.45,133.94,48.42,52.37,53.00,...,154.333333,135.678333,109.9850,104.6175,139.798039,124.570566,63.199302,137.848085,138.339787,116.128085
2021-02-22,83.96,23.63,74.25,98.39,26.47,10.20,139.47,50.88,54.30,54.85,...,140.238333,119.536667,99.1550,87.3925,114.762353,107.692453,61.523953,134.500426,133.183617,111.638085
2021-02-23,85.53,24.23,75.81,99.63,26.06,11.16,145.24,52.10,55.05,55.77,...,142.736667,123.536667,87.9200,85.9750,123.046667,113.270755,62.286279,132.853617,119.534894,105.554043
2021-02-24,87.25,25.30,78.16,103.31,28.16,11.84,150.06,54.67,56.70,56.65,...,144.465000,126.061667,97.5275,100.7775,127.957451,117.192264,63.974884,143.045957,121.992553,108.229362
2021-02-25,84.64,25.59,78.15,102.35,26.75,11.30,149.05,53.03,55.76,55.07,...,138.656667,119.348333,115.1050,109.7300,131.530588,121.559245,64.381163,125.468723,117.577872,103.360426

In [39]:
#need to add all the sentiment scores - would be best to automate...

In [40]:
csv_test_list = ['../data/sentiment_new/direct_financial/d_f_chevron.csv']
df_chevron = pd.read_csv(csv_test_list[0])
column_name = csv_test_list[0].replace(
    '../data/sentiment_new/direct_financial/','').replace(
    '../data/sentiment_new/indirect_financial/','').replace(
    '../data/sentiment_new/direct_global/','').replace(
    '../data/sentiment_new/indirect_global/','').replace('.csv', '')

In [41]:
column_name

'd_f_chevron'

In [42]:
df_chevron.rename(columns = {'Index':column_name}, inplace=True)
df_chevron.set_index(pd.to_datetime(df_chevron['DateTime']), inplace=True)
df_chevron.drop(columns=['DateTime', 'Count'], inplace=True) #drop unused columns
df_chevron.fillna(0, inplace=True) #dates which have no sentiment scores get zeroes as neither positive nor negative
df_chevron #preview / confirm

            d_f_chevron
DateTime
2005-05-09        -0.20
2005-05-10         0.00
2005-05-11         0.00
2005-05-12         0.00
2005-05-13         0.00
...                 ...
2021-03-13         0.00
2021-03-14         0.00
2021-03-15         0.00
2021-03-16        -0.20
2021-03-17        -0.02

[5792 rows x 1 columns]

this is how all sentiment dfs should look prior to join; now, to automate this process and run all the csvs through the same transformation

In [43]:
csv_list = [ #list of all the sentiment csv docs
    '../data/sentiment_new/direct_financial/d_f_chevron.csv',
    '../data/sentiment_new/direct_financial/d_f_drilling.csv',
    '../data/sentiment_new/direct_financial/d_f_exxon.csv',
    '../data/sentiment_new/direct_financial/d_f_fossil_fuel.csv',
    '../data/sentiment_new/direct_financial/d_f_marathon_oil.csv',
    '../data/sentiment_new/direct_financial/d_f_occidental_petroleum.csv',
    '../data/sentiment_new/direct_financial/d_f_oil.csv',
    '../data/sentiment_new/direct_financial/d_f_oilfield.csv',
    '../data/sentiment_new/direct_financial/d_f_phillips_66.csv',
    '../data/sentiment_new/direct_financial/d_f_pipeline.csv',
    '../data/sentiment_new/direct_financial/d_f_valero.csv',
    '../data/sentiment_new/direct_global/d_g_chevron.csv',
    '../data/sentiment_new/direct_global/d_g_drilling.csv',
    '../data/sentiment_new/direct_global/d_g_exxon.csv',
    '../data/sentiment_new/direct_global/d_g_fossil_fuel.csv',
    '../data/sentiment_new/direct_global/d_g_oil.csv',
    '../data/sentiment_new/direct_global/d_g_oilfield.csv',
    '../data/sentiment_new/direct_global/d_g_pipeline.csv',
    '../data/sentiment_new/direct_global/d_g_valero.csv',
    '../data/sentiment_new/indirect_financial/i_f_airline.csv',
    '../data/sentiment_new/indirect_financial/i_f_carbon_footprint.csv',
    '../data/sentiment_new/indirect_financial/i_f_emissions.csv',
    '../data/sentiment_new/indirect_financial/i_f_epa.csv',
    '../data/sentiment_new/indirect_financial/i_f_greenhouse.csv',
    '../data/sentiment_new/indirect_financial/i_f_hurricane_storm.csv',
    '../data/sentiment_new/indirect_financial/i_f_pollution.csv',
    '../data/sentiment_new/indirect_financial/i_f_sanction.csv',
    '../data/sentiment_new/indirect_financial/i_f_solar.csv',
    '../data/sentiment_new/indirect_financial/i_f_turbine.csv',
    '../data/sentiment_new/indirect_financial/i_f_vacation.csv',
    '../data/sentiment_new/indirect_global/i_g_airline.csv',
    '../data/sentiment_new/indirect_global/i_g_carbon_footprint.csv',
    '../data/sentiment_new/indirect_global/i_g_emissions.csv',
    '../data/sentiment_new/indirect_global/i_g_epa.csv',
    '../data/sentiment_new/indirect_global/i_g_greenhouse.csv',
    '../data/sentiment_new/indirect_global/i_g_hurricane_storm.csv',
    '../data/sentiment_new/indirect_global/i_g_pollution.csv',
    '../data/sentiment_new/indirect_global/i_g_sanction.csv',
    '../data/sentiment_new/indirect_global/i_g_solar.csv',
    '../data/sentiment_new/indirect_global/i_g_turbine.csv',
    '../data/sentiment_new/indirect_global/i_g_vacation.csv'
]

In [44]:
new.columns

Index(['phillips_66', 'bp_plc', 'valero_energy_corporation',
       'chevron_corporation', 'occidental_petroleum_corporation',
       'marathon_oil_corporation', 'pioneer_natural_resources_company',
       'conocophillips', 'exxon_mobil_corporation',
       'marathon_petroleum_corporation', 'dow_jones_transportation_average',
       'dow_jones_composite_average', 's&p_500',
       'dow_jones_industrial_average', 'dow_jones_utility_average',
       'workplaces', 'retail_and_recreation', 'grocery_and_pharmacy',
       'residential', 'transit_stations', 'parks', 'Value_ger_walk',
       'Value_ger_drive', 'Value_ger_trans', 'Value_ind_walk',
       'Value_ind_drive', 'Value_rus_walk', 'Value_rus_drive', 'Value_us_walk',
       'Value_us_drive', 'Value_us_trans', 'Value_jap_walk', 'Value_jap_drive',
       'Value_jap_trans'],
      dtype='object')

In [45]:
new

,phillips_66,bp_plc,valero_energy_corporation,chevron_corporation,occidental_petroleum_corporation,marathon_oil_corporation,pioneer_natural_resources_company,conocophillips,exxon_mobil_corporation,marathon_petroleum_corporation,...,Value_ind_walk,Value_ind_drive,Value_rus_walk,Value_rus_drive,Value_us_walk,Value_us_drive,Value_us_trans,Value_jap_walk,Value_jap_drive,Value_jap_trans
date,,,,,,,,,,,,,,,,,,,,,
2020-02-18,88.00,36.09,82.52,110.24,41.56,10.30,135.56,58.30,59.88,56.47,...,111.136667,110.881667,121.0250,112.4125,102.609804,110.113585,104.151163,132.844681,115.332553,116.532766
2020-02-19,88.36,36.25,83.23,110.74,42.51,10.47,141.17,59.26,60.34,57.69,...,113.446667,112.695000,121.1125,113.6975,105.910588,111.880377,103.913721,133.792553,116.544043,117.304043
2020-02-20,90.19,35.98,84.17,109.81,42.97,10.25,142.53,58.88,59.86,60.26,...,109.050000,114.625000,124.4000,118.4700,110.245490,116.827358,104.533488,138.852766,120.650213,121.288511
2020-02-21,89.25,35.36,82.90,109.01,42.12,10.11,142.25,58.44,59.13,59.13,...,120.485000,121.406667,131.1425,130.4325,144.047059,139.783396,117.642558,163.184255,150.928298,146.309362
2020-02-24,86.56,34.06,78.10,104.71,39.48,9.46,135.97,56.38,56.36,55.87,...,108.380000,110.791667,93.9600,100.7050,100.460980,106.576792,101.527209,146.738936,122.311064,122.677872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-19,82.31,22.87,71.53,95.80,25.42,9.45,133.94,48.42,52.37,53.00,...,154.333333,135.678333,109.9850,104.6175,139.798039,124.570566,63.199302,137.848085,138.339787,116.128085
2021-02-22,83.96,23.63,74.25,98.39,26.47,10.20,139.47,50.88,54.30,54.85,...,140.238333,119.536667,99.1550,87.3925,114.762353,107.692453,61.523953,134.500426,133.183617,111.638085
2021-02-23,85.53,24.23,75.81,99.63,26.06,11.16,145.24,52.10,55.05,55.77,...,142.736667,123.536667,87.9200,85.9750,123.046667,113.270755,62.286279,132.853617,119.534894,105.554043
2021-02-24,87.25,25.30,78.16,103.31,28.16,11.84,150.06,54.67,56.70,56.65,...,144.465000,126.061667,97.5275,100.7775,127.957451,117.192264,63.974884,143.045957,121.992553,108.229362
2021-02-25,84.64,25.59,78.15,102.35,26.75,11.30,149.05,53.03,55.76,55.07,...,138.656667,119.348333,115.1050,109.7300,131.530588,121.559245,64.381163,125.468723,117.577872,103.360426

In [46]:
for file in csv_list:
    temp = pd.read_csv(file) #read in each df in list
    col_name = file.replace(
    '../data/sentiment_new/direct_financial/','').replace(
    '../data/sentiment_new/indirect_financial/','').replace(
    '../data/sentiment_new/direct_global/','').replace(
    '../data/sentiment_new/indirect_global/','').replace('.csv', '')
    temp.rename(columns = {'Index':col_name}, inplace=True) #rename index column appropriately
    temp.set_index(pd.to_datetime(temp['DateTime']), inplace=True) #set date as index
    temp.drop(columns=['DateTime', 'Count'], inplace=True) #drop unused columns
    temp.fillna(0, inplace=True) #dates which have no sentiment scores get zeroes as neither positive nor negative
    new=new.join(temp) #join sentiment to aggregate df
print(new.shape)
new #review final look

(244, 75)

,phillips_66,bp_plc,valero_energy_corporation,chevron_corporation,occidental_petroleum_corporation,marathon_oil_corporation,pioneer_natural_resources_company,conocophillips,exxon_mobil_corporation,marathon_petroleum_corporation,...,i_g_carbon_footprint,i_g_emissions,i_g_epa,i_g_greenhouse,i_g_hurricane_storm,i_g_pollution,i_g_sanction,i_g_solar,i_g_turbine,i_g_vacation
date,,,,,,,,,,,,,,,,,,,,,
2020-02-18,88.00,36.09,82.52,110.24,41.56,10.30,135.56,58.30,59.88,56.47,...,-0.1,-0.1,-0.550000,-0.200000,0.000000,-0.500000,-0.427273,-0.175000,0.00,-0.114286
2020-02-19,88.36,36.25,83.23,110.74,42.51,10.47,141.17,59.26,60.34,57.69,...,0.0,0.0,0.000000,-0.366667,0.000000,-0.225000,-0.120000,-0.350000,0.00,-0.200000
2020-02-20,90.19,35.98,84.17,109.81,42.97,10.25,142.53,58.88,59.86,60.26,...,0.3,0.3,0.500000,-0.350000,0.000000,-0.200000,-0.366667,0.033333,0.00,-0.600000
2020-02-21,89.25,35.36,82.90,109.01,42.12,10.11,142.25,58.44,59.13,59.13,...,0.0,0.0,0.000000,0.000000,0.000000,-0.275000,-0.220000,0.000000,0.00,0.200000
2020-02-24,86.56,34.06,78.10,104.71,39.48,9.46,135.97,56.38,56.36,55.87,...,0.0,0.0,0.300000,-0.050000,0.000000,-0.466667,-0.433333,0.000000,0.00,-0.133333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-19,82.31,22.87,71.53,95.80,25.42,9.45,133.94,48.42,52.37,53.00,...,-0.2,-0.2,-0.400000,-0.283333,0.000000,-0.290909,-0.424138,-0.157143,-0.35,-0.288000
2021-02-22,83.96,23.63,74.25,98.39,26.47,10.20,139.47,50.88,54.30,54.85,...,0.0,0.0,-0.200000,0.500000,-0.245455,-0.266667,-0.490476,0.071429,-0.30,-0.117647
2021-02-23,85.53,24.23,75.81,99.63,26.06,11.16,145.24,52.10,55.05,55.77,...,-0.1,-0.1,-0.500000,-0.175000,-0.300000,-0.336364,-0.423611,-0.075000,-0.40,-0.258333
2021-02-24,87.25,25.30,78.16,103.31,28.16,11.84,150.06,54.67,56.70,56.65,...,0.1,0.1,-0.314286,-0.033333,-0.100000,-0.422222,-0.475610,-0.125000,-0.32,-0.194737
2021-02-25,84.64,25.59,78.15,102.35,26.75,11.30,149.05,53.03,55.76,55.07,...,-0.2,-0.2,-0.300000,0.100000,0.000000,-0.328571,-0.257895,0.050000,0.40,-0.123077

In [ ]:
new.to_csv('targets_')