In [1]:
import pandas as pd

In [3]:
jodi_demand = pd.read_excel('../data/Energy_Oil_Gas/JODI_oil_demand.xlsx')

In [4]:
jodi_demand.head()

,Value,Date,Sub-Sector,Super Region,Energy Product,Flow Breakdown,Time Level,Country,Unit of Measurement,Source
0,14.74,2016-05-01,JODI OIL-WORLD DATABASE,GLOBAL DATA,TOTAL OIL PRODUCTS,DEMAND,MONTHLY,BRUNEI DARUSSALAM,THOUSAND BARRELS PER DAY(KB-D),JOINT ORGANISATIONS DATA INITIATIVE - JODI
1,14.83,2017-04-01,JODI OIL-WORLD DATABASE,GLOBAL DATA,TOTAL OIL PRODUCTS,DEMAND,MONTHLY,BRUNEI DARUSSALAM,THOUSAND BARRELS PER DAY(KB-D),JOINT ORGANISATIONS DATA INITIATIVE - JODI
2,15.53,2015-06-01,JODI OIL-WORLD DATABASE,GLOBAL DATA,TOTAL OIL PRODUCTS,DEMAND,MONTHLY,BRUNEI DARUSSALAM,THOUSAND BARRELS PER DAY(KB-D),JOINT ORGANISATIONS DATA INITIATIVE - JODI
3,14.48,2015-12-01,JODI OIL-WORLD DATABASE,GLOBAL DATA,TOTAL OIL PRODUCTS,DEMAND,MONTHLY,BRUNEI DARUSSALAM,THOUSAND BARRELS PER DAY(KB-D),JOINT ORGANISATIONS DATA INITIATIVE - JODI
4,14.36,2014-07-01,JODI OIL-WORLD DATABASE,GLOBAL DATA,TOTAL OIL PRODUCTS,DEMAND,MONTHLY,BRUNEI DARUSSALAM,THOUSAND BARRELS PER DAY(KB-D),JOINT ORGANISATIONS DATA INITIATIVE - JODI

In [5]:
jodi_demand['Country'].value_counts()

SAUDI ARABIA         223
NORWAY               223
SWITZERLAND          223
HONG KONG            223
SLOVAKIA             223
                    ...
GEORGIA               43
GRENADA               24
EQUATORIAL GUINEA     18
KAZAKHSTAN             2
TAJIKISTAN             1
Name: Country, Length: 100, dtype: int64

In [6]:
#data is broken down monthly - is this useful?

In [8]:
jodi_flow = pd.read_excel('../data/Energy_Oil_Gas/JODI_US_product_flow_breakdown.xlsx')

In [9]:
jodi_flow.head()

,Value,Date,Sub-Sector,Super Region,Energy Product,Flow Breakdown,Time Level,Country,Unit of Measurement,Source
0,7471.0,2016-05-01,JODI OIL-WORLD DATABASE,GLOBAL DATA,TOTAL,CLOSING STOCKS,MONTHLY,UNITED STATES,CONVERSION FACT BARRELS-KTONS,JOINT ORGANISATIONS DATA INITIATIVE - JODI
1,7458.0,2017-04-01,JODI OIL-WORLD DATABASE,GLOBAL DATA,TOTAL,CLOSING STOCKS,MONTHLY,UNITED STATES,CONVERSION FACT BARRELS-KTONS,JOINT ORGANISATIONS DATA INITIATIVE - JODI
2,7480.0,2015-06-01,JODI OIL-WORLD DATABASE,GLOBAL DATA,TOTAL,CLOSING STOCKS,MONTHLY,UNITED STATES,CONVERSION FACT BARRELS-KTONS,JOINT ORGANISATIONS DATA INITIATIVE - JODI
3,7480.0,2015-12-01,JODI OIL-WORLD DATABASE,GLOBAL DATA,TOTAL,CLOSING STOCKS,MONTHLY,UNITED STATES,CONVERSION FACT BARRELS-KTONS,JOINT ORGANISATIONS DATA INITIATIVE - JODI
4,7447.0,2009-02-01,JODI OIL-WORLD DATABASE,GLOBAL DATA,TOTAL,CLOSING STOCKS,MONTHLY,UNITED STATES,CONVERSION FACT BARRELS-KTONS,JOINT ORGANISATIONS DATA INITIATIVE - JODI

In [11]:
jodi_flow.shape

(17760, 10)

In [12]:
#also monthly...

In [26]:
commodity = pd.read_excel('../data/Financial_Market/commodity_prices.xlsx')

In [27]:
commodity.head()

,Value,Date,Sub-Sector,Super Region,Commodity And Exchange,Frequency,Source,Indicator
0,393834.0,2020-08-07,COMMODITY PRICES,GLOBAL DATA,NYMEX CRUDE OIL FUTURES,DAILY,COMMODITY EXCHANGE,VOLUME
1,865736.0,2018-03-07,COMMODITY PRICES,GLOBAL DATA,NYMEX CRUDE OIL FUTURES,DAILY,COMMODITY EXCHANGE,VOLUME
2,345299.0,2021-01-25,COMMODITY PRICES,GLOBAL DATA,NYMEX CRUDE OIL FUTURES,DAILY,COMMODITY EXCHANGE,VOLUME
3,353417.0,2020-08-06,COMMODITY PRICES,GLOBAL DATA,NYMEX CRUDE OIL FUTURES,DAILY,COMMODITY EXCHANGE,VOLUME
4,626407.0,2018-03-06,COMMODITY PRICES,GLOBAL DATA,NYMEX CRUDE OIL FUTURES,DAILY,COMMODITY EXCHANGE,VOLUME

In [28]:
commodity['Commodity And Exchange'].value_counts()

NYMEX CRUDE OIL FUTURES                 8000
ICE BRENT CRUDE OIL FUTURES             7000
WTI CRUDE OIL (DOLLARS PER BARREL)      1000
BRENT CRUDE OIL (DOLLARS PER BARREL)    1000
Name: Commodity And Exchange, dtype: int64

In [38]:
commodity['Indicator'].value_counts()

PRICE IN USD                  2000
LOW                           2000
HIGH                          2000
SETTLE                        2000
VOLUME                        2000
CHANGE                        2000
OPEN                          2000
PREVIOUS DAY OPEN INTEREST    1000
PREV# DAY OPEN INTEREST       1000
LAST                          1000
Name: Indicator, dtype: int64

In [30]:
commodity['Date'] = pd.to_datetime(commodity['Date'])

In [36]:
com = pd.DataFrame(commodity.groupby('Date')['Value'].count())

In [37]:
com #preview

            Value
Date
2016-11-22      1
2016-11-23      1
2016-11-24      1
2016-11-25      1
2016-11-28      1
...           ...
2021-02-22     16
2021-02-23     14
2021-02-24     14
2021-02-25     14
2021-02-26     14

[1101 rows x 1 columns]

In [42]:
sec_fil = pd.read_excel('../data/Financial_Market/SEC_filings_E&P.xlsx')

In [43]:
sec_fil

,Value,Date,Super Region,Ticker,Time Level,Unit,Source,Exchange,Sub-Sector,Company Name,Industry Level 2,Industry Level 1,Company Website,Statement Type,Market Cap,Financial Metric
0,-2.010000e+08,2014-12-31,UNITED STATES,MRO,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,MARATHON OIL CORPORATION,OIL & GAS - E&P,ENERGY,HTTP://WWW.MARATHONOIL.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,EARNINGS BEFORE TAX
1,-2.380000e+08,2016-06-30,UNITED STATES,MRO,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,MARATHON OIL CORPORATION,OIL & GAS - E&P,ENERGY,HTTP://WWW.MARATHONOIL.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,EARNINGS BEFORE TAX
2,-2.400000e+07,2016-12-31,UNITED STATES,MRO,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,MARATHON OIL CORPORATION,OIL & GAS - E&P,ENERGY,HTTP://WWW.MARATHONOIL.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,EARNINGS BEFORE TAX
3,-4.200000e+08,2015-03-31,UNITED STATES,MRO,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,MARATHON OIL CORPORATION,OIL & GAS - E&P,ENERGY,HTTP://WWW.MARATHONOIL.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,EARNINGS BEFORE TAX
4,5.110000e+08,2014-06-30,UNITED STATES,MRO,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,MARATHON OIL CORPORATION,OIL & GAS - E&P,ENERGY,HTTP://WWW.MARATHONOIL.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,EARNINGS BEFORE TAX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3055,-5.220000e+05,2009-06-30,UNITED STATES,PXD,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,PIONEER NATURAL RESOURCES COMPANY,OIL & GAS - E&P,ENERGY,HTTP://WWW.PXD.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,NET INCOME - NON-CONTROLLING INT
3056,1.535200e+07,2010-03-31,UNITED STATES,PXD,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,PIONEER NATURAL RESOURCES COMPANY,OIL & GAS - E&P,ENERGY,HTTP://WWW.PXD.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,NET INCOME - NON-CONTROLLING INT
3057,7.000000e-02,2009-12-31,UNITED STATES,EOG,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,EOG RESOURCES INC.,OIL & GAS - E&P,ENERGY,HTTP://WWW.EOGRESOURCES.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,DIVIDEND PER SHARE
3058,7.000000e-02,2009-09-30,UNITED STATES,EOG,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,EOG RESOURCES INC.,OIL & GAS - E&P,ENERGY,HTTP://WWW.EOGRESOURCES.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,DIVIDEND PER SHARE
3059,7.000000e-02,2009-06-30,UNITED STATES,EOG,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,EOG RESOURCES INC.,OIL & GAS - E&P,ENERGY,HTTP://WWW.EOGRESOURCES.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,DIVIDEND PER SHARE

In [44]:
sec_int = pd.read_excel('../data/Financial_Market/SEC_filings_Integrated.xlsx')
sec_int.head()

,Value,Date,Super Region,Ticker,Time Level,Unit,Source,Exchange,Sub-Sector,Company Name,Industry Level 2,Industry Level 1,Company Website,Statement Type,Market Cap,Financial Metric
0,68000000.0,2014-12-31,UNITED STATES,XOM,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,EXXON MOBIL CORPORATION,OIL & GAS - INTEGRATED,ENERGY,HTTP://WWW.CORPORATE.EXXONMOBIL.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,INTEREST EXPENSE
1,75000000.0,2016-06-30,UNITED STATES,XOM,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,EXXON MOBIL CORPORATION,OIL & GAS - INTEGRATED,ENERGY,HTTP://WWW.CORPORATE.EXXONMOBIL.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,INTEREST EXPENSE
2,195000000.0,2016-12-31,UNITED STATES,XOM,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,EXXON MOBIL CORPORATION,OIL & GAS - INTEGRATED,ENERGY,HTTP://WWW.CORPORATE.EXXONMOBIL.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,INTEREST EXPENSE
3,88000000.0,2015-03-31,UNITED STATES,XOM,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,EXXON MOBIL CORPORATION,OIL & GAS - INTEGRATED,ENERGY,HTTP://WWW.CORPORATE.EXXONMOBIL.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,INTEREST EXPENSE
4,64000000.0,2014-06-30,UNITED STATES,XOM,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,EXXON MOBIL CORPORATION,OIL & GAS - INTEGRATED,ENERGY,HTTP://WWW.CORPORATE.EXXONMOBIL.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,INTEREST EXPENSE

In [46]:
sec_ref = pd.read_excel('../data/Financial_Market/SEC_filings_ref&mark_o&g_services.xlsx')
sec_ref.head()

,Value,Date,Super Region,Ticker,Time Level,Unit,Source,Exchange,Sub-Sector,Company Name,Industry Level 2,Industry Level 1,Company Website,Statement Type,Market Cap,Financial Metric
0,1.674000e+09,2014-12-31,UNITED STATES,PSX,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,PHILLIPS 66,OIL & GAS - REFINING & MARKETING,ENERGY,HTTP://WWW.PHILLIPS66.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,EBITDA
1,1.089000e+09,2016-06-30,UNITED STATES,PSX,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,PHILLIPS 66,OIL & GAS - REFINING & MARKETING,ENERGY,HTTP://WWW.PHILLIPS66.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,EBITDA
2,4.560000e+08,2016-12-31,UNITED STATES,PSX,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,PHILLIPS 66,OIL & GAS - REFINING & MARKETING,ENERGY,HTTP://WWW.PHILLIPS66.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,EBITDA
3,1.654000e+09,2015-03-31,UNITED STATES,PSX,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,PHILLIPS 66,OIL & GAS - REFINING & MARKETING,ENERGY,HTTP://WWW.PHILLIPS66.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,EBITDA
4,1.687000e+09,2014-06-30,UNITED STATES,PSX,QUARTER,USD,COMPANY SEC FILINGS,NEW YORK STOCK EXCHANGE,FINANCIAL STATEMENT,PHILLIPS 66,OIL & GAS - REFINING & MARKETING,ENERGY,HTTP://WWW.PHILLIPS66.COM,INCOME-STATEMENT,GREATER THAN $1BILLION MARKET CAP,EBITDA