In [1]:
import pandas as pd

In [17]:
df = pd.read_csv('../targets_with_all_features.csv')

In [18]:
df #preview

,date,phillips_66,bp_plc,valero_energy_corporation,chevron_corporation,occidental_petroleum_corporation,marathon_oil_corporation,pioneer_natural_resources_company,conocophillips,exxon_mobil_corporation,...,i_g_carbon_footprint,i_g_emissions,i_g_epa,i_g_greenhouse,i_g_hurricane_storm,i_g_pollution,i_g_sanction,i_g_solar,i_g_turbine,i_g_vacation
0,2020-02-18,88.00,36.09,82.52,110.24,41.56,10.30,135.56,58.30,59.88,...,-0.1,-0.1,-0.550000,-0.200000,0.000000,-0.500000,-0.427273,-0.175000,0.00,-0.114286
1,2020-02-19,88.36,36.25,83.23,110.74,42.51,10.47,141.17,59.26,60.34,...,0.0,0.0,0.000000,-0.366667,0.000000,-0.225000,-0.120000,-0.350000,0.00,-0.200000
2,2020-02-20,90.19,35.98,84.17,109.81,42.97,10.25,142.53,58.88,59.86,...,0.3,0.3,0.500000,-0.350000,0.000000,-0.200000,-0.366667,0.033333,0.00,-0.600000
3,2020-02-21,89.25,35.36,82.90,109.01,42.12,10.11,142.25,58.44,59.13,...,0.0,0.0,0.000000,0.000000,0.000000,-0.275000,-0.220000,0.000000,0.00,0.200000
4,2020-02-24,86.56,34.06,78.10,104.71,39.48,9.46,135.97,56.38,56.36,...,0.0,0.0,0.300000,-0.050000,0.000000,-0.466667,-0.433333,0.000000,0.00,-0.133333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,2021-02-19,82.31,22.87,71.53,95.80,25.42,9.45,133.94,48.42,52.37,...,-0.2,-0.2,-0.400000,-0.283333,0.000000,-0.290909,-0.424138,-0.157143,-0.35,-0.288000
240,2021-02-22,83.96,23.63,74.25,98.39,26.47,10.20,139.47,50.88,54.30,...,0.0,0.0,-0.200000,0.500000,-0.245455,-0.266667,-0.490476,0.071429,-0.30,-0.117647
241,2021-02-23,85.53,24.23,75.81,99.63,26.06,11.16,145.24,52.10,55.05,...,-0.1,-0.1,-0.500000,-0.175000,-0.300000,-0.336364,-0.423611,-0.075000,-0.40,-0.258333
242,2021-02-24,87.25,25.30,78.16,103.31,28.16,11.84,150.06,54.67,56.70,...,0.1,0.1,-0.314286,-0.033333,-0.100000,-0.422222,-0.475610,-0.125000,-0.32,-0.194737
243,2021-02-25,84.64,25.59,78.15,102.35,26.75,11.30,149.05,53.03,55.76,...,-0.2,-0.2,-0.300000,0.100000,0.000000,-0.328571,-0.257895,0.050000,0.40,-0.123077

In [20]:
df.set_index(pd.to_datetime(df['date']), inplace=True)
df.drop(columns='date', inplace=True)
df.sort_index(inplace=True)
df #review changes

,phillips_66,bp_plc,valero_energy_corporation,chevron_corporation,occidental_petroleum_corporation,marathon_oil_corporation,pioneer_natural_resources_company,conocophillips,exxon_mobil_corporation,marathon_petroleum_corporation,...,i_g_carbon_footprint,i_g_emissions,i_g_epa,i_g_greenhouse,i_g_hurricane_storm,i_g_pollution,i_g_sanction,i_g_solar,i_g_turbine,i_g_vacation
date,,,,,,,,,,,,,,,,,,,,,
2020-02-18,88.00,36.09,82.52,110.24,41.56,10.30,135.56,58.30,59.88,56.47,...,-0.1,-0.1,-0.550000,-0.200000,0.000000,-0.500000,-0.427273,-0.175000,0.00,-0.114286
2020-02-19,88.36,36.25,83.23,110.74,42.51,10.47,141.17,59.26,60.34,57.69,...,0.0,0.0,0.000000,-0.366667,0.000000,-0.225000,-0.120000,-0.350000,0.00,-0.200000
2020-02-20,90.19,35.98,84.17,109.81,42.97,10.25,142.53,58.88,59.86,60.26,...,0.3,0.3,0.500000,-0.350000,0.000000,-0.200000,-0.366667,0.033333,0.00,-0.600000
2020-02-21,89.25,35.36,82.90,109.01,42.12,10.11,142.25,58.44,59.13,59.13,...,0.0,0.0,0.000000,0.000000,0.000000,-0.275000,-0.220000,0.000000,0.00,0.200000
2020-02-24,86.56,34.06,78.10,104.71,39.48,9.46,135.97,56.38,56.36,55.87,...,0.0,0.0,0.300000,-0.050000,0.000000,-0.466667,-0.433333,0.000000,0.00,-0.133333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-19,82.31,22.87,71.53,95.80,25.42,9.45,133.94,48.42,52.37,53.00,...,-0.2,-0.2,-0.400000,-0.283333,0.000000,-0.290909,-0.424138,-0.157143,-0.35,-0.288000
2021-02-22,83.96,23.63,74.25,98.39,26.47,10.20,139.47,50.88,54.30,54.85,...,0.0,0.0,-0.200000,0.500000,-0.245455,-0.266667,-0.490476,0.071429,-0.30,-0.117647
2021-02-23,85.53,24.23,75.81,99.63,26.06,11.16,145.24,52.10,55.05,55.77,...,-0.1,-0.1,-0.500000,-0.175000,-0.300000,-0.336364,-0.423611,-0.075000,-0.40,-0.258333
2021-02-24,87.25,25.30,78.16,103.31,28.16,11.84,150.06,54.67,56.70,56.65,...,0.1,0.1,-0.314286,-0.033333,-0.100000,-0.422222,-0.475610,-0.125000,-0.32,-0.194737
2021-02-25,84.64,25.59,78.15,102.35,26.75,11.30,149.05,53.03,55.76,55.07,...,-0.2,-0.2,-0.300000,0.100000,0.000000,-0.328571,-0.257895,0.050000,0.40,-0.123077

In [21]:
df.isnull().sum().sum() #294 nulls in total in the set

294

In [22]:
cols = list(df.columns) #create list of all column names

In [36]:
for col in cols:
    nans = df[col].isnull().sum()
    if nans > 0:
        print(col, nans) #print column name and quantity if nans are found

Value_ger_walk 2
Value_ger_drive 2
Value_ger_trans 2
Value_ind_walk 2
Value_ind_drive 2
Value_rus_walk 2
Value_rus_drive 2
Value_us_walk 2
Value_us_drive 2
Value_us_trans 2
Value_jap_walk 2
Value_jap_drive 2
Value_jap_trans 2
d_f_pipeline 80
i_f_hurricane_storm 188

In [56]:
#impute zeroes (no sentiment) for the pipeline and hurrican sentiment scores that are empty
df['d_f_pipeline'].fillna(0, inplace=True)
df['i_f_hurricane_storm'].fillna(0, inplace=True)

In [62]:
nan_values = [] #create empty list
for col in cols: #verify changes
    nans = df[col].isnull().sum()
    if nans > 0:
        print(col, nans)
        nan_values.append(col) #add ot list
nan_values #preview list

Value_ger_walk 2
Value_ger_drive 2
Value_ger_trans 2
Value_ind_walk 2
Value_ind_drive 2
Value_rus_walk 2
Value_rus_drive 2
Value_us_walk 2
Value_us_drive 2
Value_us_trans 2
Value_jap_walk 2
Value_jap_drive 2
Value_jap_trans 2

['Value_ger_walk',
 'Value_ger_drive',
 'Value_ger_trans',
 'Value_ind_walk',
 'Value_ind_drive',
 'Value_rus_walk',
 'Value_rus_drive',
 'Value_us_walk',
 'Value_us_drive',
 'Value_us_trans',
 'Value_jap_walk',
 'Value_jap_drive',
 'Value_jap_trans']

In [63]:
df.loc['05-11-2020'][nan_values]

Value_ger_walk    NaN
Value_ger_drive   NaN
Value_ger_trans   NaN
Value_ind_walk    NaN
Value_ind_drive   NaN
Value_rus_walk    NaN
Value_rus_drive   NaN
Value_us_walk     NaN
Value_us_drive    NaN
Value_us_trans    NaN
Value_jap_walk    NaN
Value_jap_drive   NaN
Value_jap_trans   NaN
Name: 2020-05-11 00:00:00, dtype: float64

In [64]:
df.loc['05-12-2020'][nan_values]

Value_ger_walk    NaN
Value_ger_drive   NaN
Value_ger_trans   NaN
Value_ind_walk    NaN
Value_ind_drive   NaN
Value_rus_walk    NaN
Value_rus_drive   NaN
Value_us_walk     NaN
Value_us_drive    NaN
Value_us_trans    NaN
Value_jap_walk    NaN
Value_jap_drive   NaN
Value_jap_trans   NaN
Name: 2020-05-12 00:00:00, dtype: float64

these are the 2 nan value dates, a monday and tuesday in May 2020... blank for every single metric  

ideally we'd like to keep this information intact, especially with such a small quantity of rows to begin with  

I'll try imputing the average of the next 3 days for each of these (w/th/f)

In [76]:
import numpy as np

In [80]:
np.mean([df.loc['05-13-2020'][nan_values[0]], 
        df.loc['05-14-2020'][nan_values[0]], 
        df.loc['05-15-2020'][nan_values[0]]])

79.43745098039216

In [81]:
for column in nan_values:
    df[column].fillna(np.mean([df.loc['05-13-2020'][column],
                         df.loc['05-14-2020'][column],
                         df.loc['05-15-2020'][column]]), inplace=True)

In [82]:
df.isnull().sum().sum() #verify success

0

In [83]:
df.loc['05-11-2020'][nan_values]

Value_ger_walk      79.437451
Value_ger_drive     86.726863
Value_ger_trans     78.518704
Value_ind_walk      31.050000
Value_ind_drive     27.041667
Value_rus_walk      57.265833
Value_rus_drive     64.680833
Value_us_walk      107.338039
Value_us_drive     108.420629
Value_us_trans      54.822558
Value_jap_walk      77.044326
Value_jap_drive     74.190780
Value_jap_trans     72.820780
Name: 2020-05-11 00:00:00, dtype: float64

In [84]:
df.loc['05-12-2020'][nan_values]

Value_ger_walk      79.437451
Value_ger_drive     86.726863
Value_ger_trans     78.518704
Value_ind_walk      31.050000
Value_ind_drive     27.041667
Value_rus_walk      57.265833
Value_rus_drive     64.680833
Value_us_walk      107.338039
Value_us_drive     108.420629
Value_us_trans      54.822558
Value_jap_walk      77.044326
Value_jap_drive     74.190780
Value_jap_trans     72.820780
Name: 2020-05-12 00:00:00, dtype: float64

In [85]:
#df.to_csv('../target_with_all_features_clean.csv') #save cleaned dataset

Lets try another OLS model - we can predict closing prices for all 10 targets